package day8

import Day8._

class Day8Suite extends munit.FunSuite:

  val input = """............
                |........0...
                |.....0......
                |.......0....
                |....0.......
                |......A.....
                |............
                |............
                |........A...
                |.........A..
                |............
                |............""".stripMargin

  test("antinodes 1"):
    assertEquals(Position(9, 1).antinodes(Position(6, 2)), List(Position(12, 0), Position(3, 3)))
    assertEquals(Position(9, 1).antinodes(Position(6, 1)), List(Position(12, 1), Position(3, 1)))
    assertEquals(Position(6, 1).antinodes(Position(6, 2)), List(Position(6, 0), Position(6, 3)))

  test("antinodes 2"):
    assertEquals(Position(9, 2).antinodes(Position(6, 1)), List(Position(12, 3), Position(3, 0)))
    assertEquals(Position(6, 1).antinodes(Position(9, 1)), List(Position(3, 1), Position(12, 1)))
    assertEquals(Position(6, 2).antinodes(Position(6, 1)), List(Position(6, 3), Position(6, 0)))

  test("Day8 part1 a") {
    assertEquals(part1("""..........
                         |..........
                         |..........
                         |....a.....
                         |..........
                         |.....a....
                         |..........
                         |..........
                         |..........
                         |..........""".stripMargin), 2)
  }

  test("Day8 part1 b") {
    assertEquals(part1("""..........
                         |..........
                         |..........
                         |....a.....
                         |........a.
                         |.....a....
                         |..........
                         |..........
                         |..........
                         |..........""".stripMargin), 4)
  }

  test("Day8 part1") {
    assertEquals(part1(input), 14)
  }

  test("Day8 part2") {
    assertEquals(part2(input), 1)
  }

